Update github.com/percona/go-mysql
I was getting this build error on SmartOS. Upgrading to the latest version of go-mysql fixed the build issue.
`vendor/github.com/percona/go-mysql/dsn/dsn.go:222:18: undefined: net.ConnectionsPid`